env:
  CIRRUS_CLONE_DEPTH: 1

linux_x64_task:
  container:
    cpu: 2
    memory: 2G
    image: gcc:10.3.0

  install_script:
    - apt-get update -qq
    - apt-get install -qq liblzo2-dev libssl-dev libc6-dev cmake

  build_script:
    - ./build.sh

darwin_aarch64_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest

  install_script:
    - brew install openssl@3 lzo
    - brew reinstall openssl@3

  build_script:
    - ./build.sh
